### ISSUE TITLE
Invoke-WebRequest API Error

### ISSUE THREAD

**Issue by Robo56** [tmmjelde/Valheim-Dedicated-Windows#3]
There was an issue with Invoke-WebRequest for me. The IE Engine was not available to run the API hit. I was able to fix it by adding `-UseBasicParsing` to the end of the Invoke-WebRequest line.   

![AutoUpdateIssue](https://user-images.githubusercontent.com/28912309/109862323-4f8e5580-7c2e-11eb-9929-9070a257bf1a.PNG)

**Comment by tmmjelde** [comment]
This has been fixed by NullFate (creds!). 
Please try the latest version and revert back if there are still any issues.
