### ISSUE TITLE
BuildID mismatch when steamcmd API is unreachable (503 response)

### ISSUE THREAD

**Issue by upp3r90** [tmmjelde/Valheim-Dedicated-Windows#6]
When steamCMD API is unreachable for whatever reason (e.g. 503 service unavailable), function Get-ValheimLatestVersion returns null value for BuildID and results in mismatch with current version on the periodic update check.  This results in the script erroneously interpreting the mismatch as a version update and causes the server to stop and check for an update.  Issue repeats on the update check interval until the until the mismatch is resolved.  Recommend adding logic to handle response errors in web request or null value returned for BuildID.

**Comment by NullFate** [comment]
Added a pull request that seems to fix this issue in my testing. I am not familiar with PowerShell so I don't know if I am following best practices. Please feel free to let me know how this should be done correctly or update the request.

**Comment by tmmjelde** [comment]
This has been fixed by NullFate (creds!). 
Please try the latest version and revert back if there are still any issues.

Also, I check your code NullFate. It looks good, and I consider myself picky 👍
